name: Check Heroku App Status

on:
  schedule:
    - cron: "*/30 * * * *" # This checks every 30 minutes, change as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Heroku App Status
        id: check_status
        run: |
          STATUS=$(curl -s -o /dev/null -w '%{http_code}' https://bcp-fast-api.herokuapp.com/)
          if [ "$STATUS" -eq "200" ]; then
            echo "App is up and running"
            echo ::set-output name=STATUS::UP
          else
            echo "App is down" 
            echo ::set-output name=STATUS::DOWN
          fi

      - name: Telegram Notify
        if: steps.check_status.outputs.STATUS == 'DOWN'
        uses: appleboy/telegram-action@v1.6.2
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "Your Heroku API  appears to be down."
